<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class ThreadsTest extends TestCase
{
    use DatabaseMigrations;
    /**
     * A basic test example.
     *
     * @return void
     */

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->thread = factory('App\Thread')->create();
    }

    // user can browse threads
    public function test_a_user_can_browse_threads()
    {

        $this->get('/threads')

            ->assertSee($this->thread->title);

    }

    // user can read single thread
    public function test_a_user_can_read_a_single_thread()
    {

        $this->get('/threads/'. $this->thread->id)

                    ->assertSee($this->thread->title);
    }



}
